# ===============================
# = Hibernate datasource
# ===============================
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/estate
    username: postgres
    password: postgres

  # ===============================
  # = JPA configurations
  # ===============================
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        default_schema: public

# ===============================
# = Logging configurations
# ===============================
logging:
  level:
    root: WARN
    com.singeev: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
